### ISSUE TITLE
Can't hide sidebar on post page

### ISSUE THREAD

**Issue by jebeaudoin** [vitathemes/wp-indigo#107]
Even with the latest update, I'm still getting a sidebar _area_ on my single-post page, which causes my content to appear skewed to the left (see the diagram in my original support request). When I look at the original single.php file, it appears as if there is a variable ('sidebar_display') that can be set to true or false, but the toggle for the "show sidebar" option in the theme customizer has no effect.

![bug report](https://user-images.githubusercontent.com/10992411/169713037-866a8dc5-6265-4387-9cdb-476900debb3f.png)

**Comment by mrmolaei** [comment]
Hi @jebeaudoin. Can you tell me do you have [Kirki Customizer Framework](https://wordpress.org/plugins/kirki/) installed on your website? If you want to change anything on our themes you have to install "Kirki Customizer Framework", so please make sure you have installed it and then go to theme settings: Customize -> Elements -> Sidebar Options -> Show Sidebar: turn off.
Let me know if you didn't make it or need to know anything else.

**Comment by jebeaudoin** [comment]
Yes, I have Kirki Customizer Framework installed and I have gone to: Customize -> Elements -> Sidebar Options -> Show Sidebar: turn off. I've attached another screenshot to verify that for you.

![Screen Shot 2022-05-23 at 10 21 29 AM](https://user-images.githubusercontent.com/10992411/169843742-2906a625-ab87-4692-bc0f-0e6406a59635.png)

When I inspect the elements, here's a screenshot of the styling:

![Screen Shot 2022-05-23 at 10 36 16 AM](https://user-images.githubusercontent.com/10992411/169843795-1f8074c0-f014-4381-aa3a-0254b13c2e19.png)

And here's where the problem shows up. I'm not a developer, but it looks like the default 100% width for <article is="post-1" class="c-single post-1 ...>" is being overwritten with a 555 pixel width.

![Screen Shot 2022-05-23 at 10 37 25 AM](https://user-images.githubusercontent.com/10992411/169844222-85a230e0-45c3-4464-a6aa-a6eb2e5681f1.png)

If I narrow the browser on my desktop to specific width, the navigation menu switches to a browser (expected behavior) and suddenly the post content appears correctly distributed.

Any ideas?

Jack

**Comment by mrmolaei** [comment]
I'm sorry for the issue you had with our theme. We will review the code and will make sure the issue never happens again. Temporary you can stick with the custom style codes you added to your website. We will have an update soon to fix this bug. Thank you for reporting the bug. @jebeaudoin
