### ISSUE TITLE
Disable Kiriki help notice

### ISSUE THREAD

**Issue by MHitMaN** [vitathemes/wp-indigo#17]
![screenshot-demo vitathemes com-2019 08 18-16_31_30](https://user-images.githubusercontent.com/20977558/63252947-1548a780-c286-11e9-80dc-4954bae76445.png)

**Comment by mostafasoufi** [comment]
https://github.com/vitathemes/wp-indigo/commit/339de852e0a55c2bae58300518646cebd37472e0#r34738519

**Comment by MHitMaN** [comment]
Done.
