### ISSUE TITLE
Reduce space below menu bar

### ISSUE THREAD

**Issue by Hxlu-bit** [vitathemes/wp-indigo#51]
Hello

I really love the theme thank you! I'm building this: https://andynarracott.com/

Is it possible to reduce the space below the menu bar? I'm using a MacBook Air so not a very big screen.

![Screenshot 2020-11-18 at 17 04 59](https://user-images.githubusercontent.com/74657331/99562621-3d124800-29c0-11eb-981d-3da50d705d6f.png)

Thanks

**Comment by Hxlu-bit** [comment]
Is this going to be possible?

**Comment by mostafasoufi** [comment]
As a temporary solution, you can create a child-theme to add your custom CSS in the child-theme or the faster way, overwriting the CSS through **Appearance > Customize > Additional CSS**


```
.page {
    margin-top: 171px !important;
}
```
