### ISSUE TITLE
Profile section not shown on Home page

### ISSUE THREAD

**Issue by Hxlu-bit** [vitathemes/wp-indigo#57]
When customising theme > Elements, The Show Profile Section is switched to 'On''

Profile section is only appearing on Blog page and not Home page or any other page.
![Screenshot 2021-01-08 at 10 52 13](https://user-images.githubusercontent.com/74657331/104007301-a4b66980-519f-11eb-93b9-e8e015227780.png)
![Screenshot 2021-01-08 at 10 52 28](https://user-images.githubusercontent.com/74657331/104007303-a5e79680-519f-11eb-91ce-5e4a9bed3b75.png)

**Comment by Hxlu-bit** [comment]
I found a work around

**Comment by mostafasoufi** [comment]
sounds good

**Comment by frnsimoes** [comment]
What work around did you find? @Hxlu-bit
