### ISSUE TITLE
RSS Icon not showing in footer

### ISSUE THREAD

**Issue by tomjbradley** [vitathemes/wp-indigo#59]
**Problem**
When you add the footer text an invisible link appears that opens the rss feed for the site. There should be some sort of icon there so users can see the link and to make the copyright text look more centered.

**Steps to reproduce**
1. Install wordpress
2. Install the WP Indigo theme
3. Open the customizer > elements and type anything into the _Copyright Text_ field

**Expected Output**
I expected there to be an RSS icon, I presume this was what was intended and thus this is just a bug.

**System Setup**
Operating System: Windows 10
Local Development Environment: XAMPP
Wordpress Version: 5.7

**Additional Info**
I have no other plugins installed and I've tested this on a fresh copy of wordpress, so I think its a bug in the code.

**Comment by mostafasoufi** [comment]
Thank you for the PR, I've recently confirmed and merged it to `development` and shall release it for the next version.

**Comment by tomjbradley** [comment]
Great! Again thanks for the theme
