### ISSUE TITLE
Add social icons for Dribble and Behance

### ISSUE THREAD

**Issue by tomjbradley** [vitathemes/wp-indigo#60]
It would be nice if there were options to add social links for design platforms like dribble and behance. At the moment all the options are a bit more developer oriented, it would be nice to have some stuff for designers too. I myself do some development and some design, I've already got my Github profile on my site, but I'd like to be able to link to these platforms on my site so I can show my design to potential employers too.

**Comment by mostafasoufi** [comment]
Good point! merged!
