### ISSUE TITLE
Can't use profile element as home page without "Nothing Found" below

### ISSUE THREAD

**Issue by ThePhilgrim** [vitathemes/wp-indigo#66]
![Screenshot 2021-03-29 at 15 54 45](https://user-images.githubusercontent.com/76887896/112847744-ae1ce700-90a7-11eb-9d70-c84b5550e223.png)
When no page is chosen, the profile is there but with a "Nothing Found" part below.

![Screenshot 2021-03-29 at 15 55 14](https://user-images.githubusercontent.com/76887896/112847781-b412c800-90a7-11eb-93e1-a02ae5789545.png)
When I choose "Home" as my static page, the profile disappears.

I'd like to have the profile with my page below it. Is it possible?

Thanks

**Comment by mrmolaei** [comment]
Hi @ThePhilgrim, at this time you can not have your content below the profile section. The homepage has a custom page template named "Home", you have to set it on your homepage. If you are really need to have your content on homepage, I made a custom "Home" page template for you. Please, follow steps below:

1. Unzip [home.zip](https://github.com/vitathemes/wp-indigo/files/6268825/home.zip)
2. Replace unzipped file (home.php) with `page-templates/home.php`
3. Set "Home" Custom page template to your homepage
4. Add your content

**Comment by ThePhilgrim** [comment]
> Hi @ThePhilgrim, at this time you can not have your content below the profile section. The homepage has a custom page template named "Home", you have to set it on your homepage. If you are really need to have your content on homepage, I made a custom "Home" page template for you. Please, follow steps below:
> 
> 1. Unzip [home.zip](https://github.com/vitathemes/wp-indigo/files/6268825/home.zip)
> 2. Replace unzipped file (home.php) with `page-templates/home.php`
> 3. Set "Home" Custom page template to your homepage
> 4. Add your content

Absolutely amazing! Thank you very much!
