### ISSUE TITLE
Profile icon

### ISSUE THREAD

**Issue by geekimposter** [vitathemes/wp-indigo#72]
![Screen Shot 2021-05-26 at 9 02 27 PM](https://user-images.githubusercontent.com/920004/119764154-c15cf080-be65-11eb-8774-3c07df165f07.png)
How do I insert a profile pic into the theme like in the demo page?

**Comment by geekimposter** [comment]
I figured it out.  it is the site logo. Thanks!

**Comment by seandakid** [comment]
My profile icon is showing up in the top left of the website, not centered like the demo. Any ideas why?

**Comment by seandakid** [comment]
Figured it out. It requires you to install the Kirki plugin. Then the option is available under Customize-->Site Identity-->Profile Image
