### ISSUE TITLE
blog page template missing.

### ISSUE THREAD

**Issue by inithin683** [vitathemes/wp-indigo#80]
the template for the blog page is missing from page-templates/

**Comment by nimaprmdi** [comment]
Hello @inithin683.

To create a blog page, Simply create a page called blog ( or anything you want ) and go to `Settings` > `Reading` and Select `A static page` option and set post page to your `blog` page.

useful link : https://bit.ly/3wLEzpY

Thank you for posting issue. If there was any problem feel free to ask.
