### ISSUE TITLE
Social Networks  

### ISSUE THREAD

**Issue by arashmiri** [vitathemes/wp-indigo#81]
Social media icons are not displayed (github , email)

**Comment by mostafasoufi** [comment]
I'm not entirely sure what's your theme's version, if It's the latest version, then it should work properly same as the demo.
https://demo.vitathemes.com/indigo/

Have you filled out those customization fields?

**Comment by arashmiri** [comment]
its latest
yes 
Facebook, Twitter, Instagram, Linkedin work, but the rest of the icons do not
![Social Networks](https://user-images.githubusercontent.com/67855391/126664285-138e77fb-9a2b-43f9-a68b-0e666cc6fa5d.png)

**Comment by mostafasoufi** [comment]
I suppose the wrong value caused the issue, please try to enter the correct value.

**Comment by arashmiri** [comment]
I Filled the field with the appropriate values But the problem is the same as before
Could it be because I Run at localhost ?

**Comment by nimaprmdi** [comment]
Hello @arashmiri

We have made some changes to the new version, And the update is available at WordPress [themes directory](https://wordpress.org/themes/wp-indigo). If you see any problems, please let us know. 

Thank you.

**Comment by mostafasoufi** [comment]
I suppose the issue can be close due to the last release.
